# Generated by Django 5.1.4 on 2026-05-05 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('button_text', models.CharField(blank=True, default='Смотреть', max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Изображение (мобильное)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Мета-описание')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Magazin Odejdi', max_length=100)),
                ('site_description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('vk_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('delivery_info', models.TextField(blank=True, verbose_name='Информация о доставке')),
                ('return_policy', models.TextField(blank=True, verbose_name='Политика возврата')),
                ('free_delivery_from', models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Бесплатная доставка от (руб)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Ключ секции')),
                ('label', models.CharField(max_length=200, verbose_name='Описание')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Изображение')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='Ссылка')),
                ('is_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page')),
            ],
            options={
                'verbose_name': 'Секция страницы',
                'verbose_name_plural': 'Секции страниц',
                'ordering': ['sort_order'],
                'unique_together': {('page', 'key')},
            },
        ),
    ]
