# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
